--CREATE DATABASE TINYVID
--USE TINYVID


CREATE TABLE MEMBERSHIP
(MEM_NUM CHAR(3) PRIMARY KEY,
MEM_FNAME VARCHAR(20),
MEM_LNAME VARCHAR(20),
MEM_STREET VARCHAR(30),
MEM_CITY VARCHAR(15),
MEM_ZIP NUMERIC (5,0) UNIQUE,
MEM_BALANCE NUMERIC (4,0))

INSERT INTO MEMBERSHIP VALUES('102', 'TAMI', 'DAWNSON', '2632 TAKLI CIRCLE', 'NORENE', 37136, 11)
INSERT INTO MEMBERSHIP VALUES('103', 'curt', 'kngiht', '4025 cronell court', 'flatgap', 41219, 6)



CREATE TABLE RENTAL
(RENT_NUM CHAR(4) PRIMARY KEY,
RENT_DATE DATE,
MEM_NUM CHAR(3)
CONSTRAINT RENTAL_MEM_NUM_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBERSHIP (MEM_NUM))


CREATE TABLE PRICE
(PRICE_CODE CHAR(1) PRIMARY KEY,
PRICE_DESCRIPTION VARCHAR(30),
PRICE_RENTFEE NUMERIC (3, 2),
PRICE_DAILYLATEFEE NUMERIC( 3, 2))

INSERT INTO price VALUES('1', 'standard', 2, 1)
INSERT INTO price VALUES('2', 'new release', 3.5, 3)



CREATE TABLE MOVIE
(MOVIE_NUM CHAR(4) PRIMARY KEY,
MOVIE_NAME VARCHAR (20),
MOVIE_YEAR varchar(4),
MOVIE_COST NUMERIC (4, 2),
MOVIE_GENRE VARCHAR(14),
PRICE_CODE CHAR(1),
CONSTRAINT MOVIE_PRICE_CODE_FK FOREIGN KEY (PRICE_CODE) REFERENCES PRICE (PRICE_CODE))

insert into movie values('1234', 'the cesar fam', '2007', 39.95, 'family', '2')
insert into movie values('1235', 'smkoket mount', '2004', 59.95, 'action', '1')

CREATE TABLE VIDEO
(VID_NUM CHAR(5) PRIMARY KEY,
VID_INDATE DATE,
MOVIE_NUM CHAR(4),
CONSTRAINT VIDEO_MOVIE_NUM_FK FOREIGN KEY (MOVIE_NUM) REFERENCES MOVIE)


CREATE TABLE DETAILRENTAL
(RENT_NUM CHAR(4),
VID_NUM CHAR(5),
PRIMARY KEY (RENT_NUM, VID_NUM),
DETAIL_FEE NUMERIC (3,0) NOT NULL,
DETAIL_DUEDATE DATE,
DETAIL_RETURNDATE DATE,
DETAIL_DAILYLATEFEE NUMERIC (2,0) NOT NULL, 
CONSTRAINT DETAILRENTAL_RENT_NUM_FK FOREIGN KEY (RENT_NUM) REFERENCES RENTAL,
CONSTRAINT DETAILRENTAL_VID_NUM_FK FOREIGN KEY (VID_NUM) REFERENCES VIDEO)


--1 (2 insteaad of 3 cuz theres no 3 in price table

UPDATE MOVIE
SET PRICE_CODE = '2'
WHERE MOVIE_GENRE = 'action'



--2

UPDATE MOVIE
SET MOVIE_COST = MOVIE_COST + 0.50

SELECT* FROM MOVIE

--3 (1232 INSTEAD 1245 CUZ I DIDNT INSERTIT

update MOVIE
SET MOVIE_YEAR = '2014'
WHERE  MOVIE_NUM = '1232'


--4.


ALTER TABLE PRICE
ADD PRICE_RENTDAYS INT

ALTER TABLE PRICE
ADD CONSTRAINT PRICE_PRICE_RENTDAYS_CK CHECK (PRICE_RENTDAYS > 10)
